name: 'CI Pipeline'
on:
  workflow_dispatch:

jobs:
  component-tests: 
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório.
        uses: actions/checkout@v4

      - name: Instalação do Node.js.
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      
      - name: Instalação do Cypress.
        run: npm install cypress

      - name: Instalação das dependências.
        run: npm install
      
      - name: Execução dos testes.
        run: npx cypress run
      
      